django_t1/urls.py
# from django.conf.urls import url, include
#
# # from store.views import index
# from store.views import set_cookies, user
#
# urlpatterns = [
#     # url(r'^$',index),#静态路由
#     url(r'^set_cookies$', set_cookies),  # 静态路由
#     url(r'^admin/', admin.site.urls),  # 静态路由
#     url(r'^store', include('store.urls')),#静态路由
#     动态url P 表示捕获到的数字变成遗个叫做id 的参数
#     url(r'blog/(?P<id>[0-9]+)$', user, {"name": "blog_"}),
#     url(r'^user/', include('store.urls'))  # 路由包含使用方法
#
# ]
from django.conf.urls import url, include
from django.views.generic import TemplateView  # TemplateView 内至views
from django.contrib import admin

urlpatterns = [
    # 对照下面 如果有人访问这个网址 detail.html 那我们就去渲染detail.html 这个目录
    # 看似相同 不过前面的的是路由讯息（注意要记加^S起始和结束符号)后面的是模板
    url('^addrManage.html$', TemplateView.as_view(template_name="addrManage.html"), ),
    url('^detail.html$', TemplateView.as_view(template_name="detail.html"), {"storerecommend": range(5)}),
    url('^index.html$', TemplateView.as_view(template_name="index.html"), ),
    url('^list.html$', TemplateView.as_view(template_name="list.html"), {"productlist": range(12)}),
    url('^login.html$', TemplateView.as_view(template_name="login.html"), ),
    url('^orderCenter.html$', TemplateView.as_view(template_name="orderCenter.html"), ),
    url('^register.html$', TemplateView.as_view(template_name="register.html"), ),
    url('^shoppingCart.html$', TemplateView.as_view(template_name="shoppingCart.html"), ),
    url('^temp.html$', TemplateView.as_view(template_name="temp.html"), ),
    url(r"^store/", include("store.urls")),
    url(r'^admin/', admin.site.urls),  # 静态路由
    url(r'^admin_ckeditor/', include("ckeditor_uploader.urls"))
]

store/urls.py
from django.conf.urls import url
from .views import detail

urlpatterns = [
    # url(r'^upload$', upload),
    # url(r'upload_pic$', upload, {"path": "pic"}),
    # url(r'upload_html$', upload, {"path": "html"}),
    # url(r'upload_js$', upload, {"path": "js"}),
    # url(r'^(?P<id>[0-9]+)$', user, {"name": "_chen"}),
    # url(r'^login$', user, {"name": "_chen", "id": ""}),  # 这三个url 前缀是一样的
    # url(r'^reg$', user, {"name": "_chen", "id": ""}),  # 这三个url 前缀是一样的
    # url(r'^logout$', user, {"name": "_chen", "id": ""}),  # 这三个url 前缀是一样的
    url(r'detail.html', detail),
]

store/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from ckeditor_uploader.fields import RichTextUploadingField


# Create your models here.
class Brand(models.Model):
    title = models.CharField("品牌名称", max_length=200)

    class Meta:
        verbose_name = "品牌"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title


class Category(models.Model):
    title = models.CharField("分类名称", max_length=200)

    class Meta:
        verbose_name = "分类"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title


class Product(models.Model):  # 继承于django模型
    GENDER_CHOICES = (
        (1, "男士"),
        (2, "女士"),
        (3, "情侣"),
    )
    TYPE_CHOICES = (
        (1, "上装"),
        (2, "下装"),
        (3, "鞋履"),
        (4, "配饰"),
    )

    title = models.CharField("商品名称", max_length=200, help_text="输入商品名称")  # 字符型态
    # 分类 一对多 每个分类有多个商品 一对多时 第一个参数要写我们自己写的类（Category）
    #  on_delete是django 2.0 才开始要写的关联方法 意思就是如果有关连的时候就不予许删除
    # 先设定為空 null=True
    category = models.ForeignKey(Category, verbose_name="所属分类", on_delete=models.PROTECT, null=True)
    """
    DecimalField 小数记量高精度用于计算金额 decimal_places=2 小数点后的位数
    max_digits=8 总的长度
    validators=[MinValueValidator(0) 验证器 验证最小数值為0
    """
    brand = models.ForeignKey(Brand, verbose_name="所属品牌", on_delete=models.PROTECT, null=True)

    price = models.DecimalField("吊牌价", default=0, decimal_places=2, max_digits=8,
                                validators=[MinValueValidator(0), ])

    sales_price = models.DecimalField("销售价", default=0, decimal_places=2, max_digits=8,
                                      validators=[MinValueValidator(0), ], help_text="输入价格不可小于0")

    sales_count = models.IntegerField("销量", default=0, validators=[MinValueValidator(0), ])

    num = models.IntegerField("库存", default=0, validators=[MinValueValidator(0), ])

    discount = models.IntegerField("折扣比例", default=100, validators=[MinValueValidator(1), MaxValueValidator(100)],
                                   help_text="填写1～100,100表示原价")

    # size = models.ForeignKey(Size, on_delete=models.PROTECT, verbose_name="尺码")
    # 资料库内存的是整数
    gender = models.IntegerField("性别", default=1, choices=GENDER_CHOICES, db_index=True)

    type = models.IntegerField("类型", default=1, choices=TYPE_CHOICES, db_index=True)

    content = RichTextUploadingField("商品详情", null=True, blank=True)  # 附文本可存较大的文字量

    def get_discount_display(self):
        return self.discount / 10

    class Meta:
        verbose_name = "商品"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title


class ProductPic(models.Model):
    product = models.ForeignKey(Product, on_delete=models.PROTECT, verbose_name="商品", related_name="pic")
    title = models.CharField("商品标题", max_length=200)
    is_main = models.BooleanField("主图", default=False)
    order = models.IntegerField("序号", default=0, help_text="数字越小,位址越前")
    img = models.ImageField("图片地址", )

    class Meta:
        verbose_name = "商品图片列表"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title + f'(商品ID = {self.product_id})'

store/views.py
from django.shortcuts import render, HttpResponse
import os
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from django.template import loader
from .models import Product
from django.shortcuts import *


# 笔记 以隐藏
# Create your views here.
# 创建视图
# def index(request):
#     method = request.method
#     if method == 'GET':
#         content = 'get'
#     elif method == 'POST':
#         content = 'post'
#     print(request.build_absolute_uri())
#     response = HttpResponse(content, )
#
#     return response


# cookie 处理
# def set_cookies(request):
#     content = ' welcome to my first web'
#     key = 'not_robot'
#     code = '123456'  # 验证马可以根据request 进行hash计算
#     # 验证cookies
#     if request.COOKIES.get(key, '') != code:  # 读取cookie 并进行验证
#         # 如果没有cookies 发送 set_cookies + http302 要求重新访问
#         response = HttpResponse()
#         response.set_cookie(key, code)  # 设置cookie
#         response.status_code = 302  # 要求浏览器进行跳转
#         response['Location'] = request.build_absolute_uri()  # 要求重新访问的网址就是本地地址
#     else:
#         response = HttpResponse(content)
#     return response


# user 测试
# def user(request, id, name="index"):
#     content = f'欢迎查看{name}页面当前id是{id}'  # 也可以写成f'欢迎查看{name}页面当前id是%s'%id
#     return HttpResponse(content)


# uplode 上传功能 上传档案范例
# def upload(request, path=""):
#     html = render(request, "upload.html", locals())
#
#     if request.method == "POST":  # 只有在post 模式下才会传输 后端才会解析body
#         file = request.FILES.get("gavin", "")  # 类似字典
#
#         if file:  # 检查文件讯息
#             # 保存到服务器
#             file_path = os.path.join(settings.MEDIA_ROOT, path)
#             file_name = "new_name_" + file.name
#             if not os.path.exists(file_path):  # 判断文件夹是否存在
#                 os.makedirs(file_path)
#             if os.path.exists(file_name):  # 判断文件存在就重新命名
#                 file_name = '_' + file_name
#             # 1.指定保存路径
#
#             # 2. 保存文件到硬碟
#             with open(file_path + file_name, 'wb+') as f:
#                 # f.write(file.read())#不推荐 如果档案过大 会出现记忆体不够的问题
#                 for chunk in file.chunks():  # 大文件处里方式
#                     f.write(chunk)
#             url_path = request.build_absolute_uri()
#             html_suf = " <script>alert(' 上传资料成功 ');</script> <p>文件地址 :  </p> " + url_path + '/' + file_name
#             # <script>alert('  ');</script>  网页弹出提示讯息写法
#             return HttpResponse(html_suf)
#         else:
#
#             back = "<script>alert(' 未输入资料 ');</script>"
#
#             return HttpResponse(back)
#     return html
# 解决csrf 验证问题的方法在 upload.html
# 渲染变量
# def upload(request):
#     template = loader.get_template("upload.html")  # 调用模板引擎
#     context = {"html": "123", "list": [1, 2]}  # 类似print 的功能直接输出
#     html = template.render(context)
#     return HttpResponse(html)

def detail(request):
    """
    商品详情

    """

    id = request.GET.get("id", "")  # 先从request 接收参数
    if not id.isdigit():
        raise Http404()# 首先判断是不是数字不是数字返回404
    obj = get_object_or_404(Product, id=id)  # 然后将参数丢给模型去查询 如果拿到数据渲染模板 如果没有拿到数据返回404

    return render(request, "detail.html", locals())

templates/addrManage.html
{% load staticfiles %}<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
		<link rel="stylesheet" href="{% static "css/bootstrap/bootstrap-theme.min.css" %}"/>
		<link rel="stylesheet" href="{% static "css/bootstrap/bootstrap.min.css" %}"/>
		<link rel="stylesheet" href="{% static "css/common.css" %}"/>
		<link rel="stylesheet" href="{% static "css/sidebarMenu.css" %}"/>
		<link rel="stylesheet" href="{% static "css/addrManage.css" %}"/>
		<title>地址管理</title>
	</head>
	<body class="paged">
		{% include "head.html" %}
		<main class="main" role="main">
			<div class="container addr-manage">
				<ol class="breadcrumb">
					<li>
						<a href="#">首页</a>
					</li>
					<li>
						<a href="#">个人中心</a>
					</li>
					<li class="active">订单中心</li>
				</ol>
				<div class="row">
					<div class="col-xs-12 col-sm-2 sidebar-menu">
						<h4>个人中心<small>UCENTER</small></h4>
						<img src="{% static "img/UCENTER/U.png" %} "width="100%">
						<a href="#orderMeun" class="nav-header menu-first collapsed" data-toggle="collapse">
							<span class="glyphicon glyphicon-expand" aria-hidden="true"></span>交易管理
						</a>
						<ul id="orderMeun" class="nav nav-list collapse menu-second">
							<li>
								<a href="#">我的订单</a>
							</li>
							<li>
								<a href="#">我的收藏</a>
							</li>
							<li>
								<a href="#">我的动脑币</a>
							</li>
							<li>
								<a href="#">我的红包</a>
							</li>
							<li>
								<a href="#">我的优惠券</a>
							</li>
							<li>
								<a href="#">我的邀请好友</a>
							</li>
							<li>
								<a href="#">我的礼品卡</a>
							</li>
							<li>
								<a href="#">我的VIP</a>
							</li>
						</ul>
						<a href="#serviceCenter" class="nav-header menu-first collapsed" data-toggle="collapse">
							<span class="glyphicon glyphicon-expand" aria-hidden="true"></span>服务中心
						</a>
						<ul id="serviceCenter" class="nav nav-list collapse menu-second">
							<li>
								<a href="#">我的退/换货</a>
							</li>
							<li>
								<a href="#">我的发票</a>
							</li>
							<li>
								<a href="#">我的咨询</a>
							</li>
							<li>
								<a href="#">我的评论</a>
							</li>
							<li>
								<a href="#">我的消息</a>
							</li>
							<li>
								<a href="#">在线客服</a>
							</li>
						</ul>
						<a href="#messMenu" class="nav-header menu-first collapsed" data-toggle="collapse">
							<span class="glyphicon glyphicon-expand" aria-hidden="true"></span>个人信息管理
						</a>
						<ul id="messMenu" class="nav nav-list collapse menu-second">
							<li>
								<a href="#">编辑个人资料</a>
							</li>
							<li>
								<a href="#">账号安全</a>
							</li>
							<li>
								<a href="#">地址管理</a>
							</li>
						</ul>
					</div>
					<div class="col-xs-12 col-sm-10 content-right">
						<h4>地址管理</h4>
						<div class="addr-box">
							<div class="reminder">
								为提高配送时效，请您尽快准确填写四级地址
							</div>
							<div class="addr-box-title">
								<span class="glyphicon glyphicon-play-circle" aria-hidden="true"></span>添加新地址
							</div>
							<div class="addr-box-content">
								<form class="form-horizontal">
									<div class="form-group">
										<label for="consignee">收货人姓名</label>
										<div class="col-sm-3">
											<input type="text" class="form-control" id="consignee">
										</div>
										<span><span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>请输入收货人姓名</span>
									</div>
									<div class="form-group">
										<label for="address">省份</label>
										<div class="col-sm-8">
											<select class="form-control">
												<option>请选择省份</option>
											</select>
											<select class="form-control">
												<option>请选择市</option>
											</select>
										</div>
									</div>
									<div class="form-group">
										<label for="address">地址</label>
										<div class="col-sm-6">
											<input type="text" class="form-control" id="address" placeholder="">
										</div>
										<span><span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>请填写详细地址</span>
									</div>
									<div class="form-group">
										<label for="zipCode">邮编</label>
										<div class="col-sm-3">
											<input type="text" class="form-control" id="zipCode" placeholder="">
										</div>
										<span><span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>请输入收货人所在地邮编号码</span>
									</div>
									<div class="form-group">
										<label for="fixedTel">固定电话</label>
										<div class="col-sm-3">
											<input type="text" class="form-control" id="fixedTel" placeholder="">
										</div>
										<span><span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>请输入你的联系电话，可以为空哦</span>
									</div>
									<div class="form-group">
										<label for="mobilePhone">手机号码</label>
										<div class="col-sm-3">
											<input type="text" class="form-control" id="mobilePhone" placeholder="">
										</div>
										<span><span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>填写手机号便于接收发货和收获通知</span>
									</div>
									<button type="submit" class="btn btn-default submit-addr">
									  	提交信息
									  	<span class="glyphicon glyphicon-play" aria-hidden="true"></span>
									  </button>
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
		</main>
		{% include "footer.html" %}
		<script type="text/javascript" src="js/jquery-3.2.1.min.js"></script>
		<script type="text/javascript" src="js/bootstrap/bootstrap.min.js"></script>
		<script>
		</script>
	</body>

</html>

templates/detail.html
{% load staticfiles %}<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
		<link rel="stylesheet" href="{% static "css/bootstrap/bootstrap-theme.min.css" %} " />
		<link rel="stylesheet" href="{% static "css/bootstrap/bootstrap.min.css" %} " />
		<link rel="stylesheet" href="{% static "css/common.css" %} " />
		<link rel="stylesheet" href="{% static "css/detail.css" %} " />
		<title>商品详情</title>
	</head>

	<body class="paged">
		{% include "head.html" %}
		<main class="main" role="main">
			<div class="container">
				<ol class="breadcrumb">
					<li>
						<a href="#">首页</a>
					</li>
					<li>
						<a href="#">{{ obj.get_gender_display  }}</a>
					</li>
					<li>
						<a href="#">{{ obj.get_type_display }}</a>
					</li>
					<li class="active">{{ obj.category.title }}</li>
				</ol>
				<div class="row">
					<div class="col-xs-12 col-sm-5 product-show-img">
						<div class="mainImg" id="largePicDiv">
							<div id="detailPic" class="big_pic" style="background-image: url('{% static "img/detail/item_01.jpg" %}');"></div>
							<div class="zoom_pup" id="move"></div>
						</div>
						<div class="allImg">
							<img class="active" src="{% static "img/detail/item_01.jpg" %}" />
							<img class="" src="{% static "img/detail/item_02.jpg" %}" />
							<img class="" src="{% static "img/detail/item_03.jpg" %}" />
							<img class="" src="{% static "img/detail/item_04.png" %}" />
						</div>
					</div>
					<div class="col-xs-12 col-sm-7 product-show-msg">
						<!--信息列表 begin-->
						<table class="table product-msg-box">
							<tbody>
								<tr>
									<td colspan="2">
										<h4 class="product-name">{{obj.title|default:"未命名"}}</h4></td>
								</tr>
								<tr>
									<td class="price-tr">
										<span>吊牌价：<span class="old-price">{{ obj.pric }}</span></span>
										<span>促销价：<span class="new-price">{{ obj.sales_pric }}</span></span>
										<span class="discount">{{ obj.get_discount_display}}折</span>
										<span>登陆后即可查看vip价格</span>
										<span><a class="tx_red" href="login.html">立即登录</a></span>
									</td>
								</tr>
								<tr>
									<td class="color-tr">
										<span class="size">尺码：<a>S</a><a>M</a><a>L</a><a>XL</a></span>
										<span class="color">颜色：<a class="black"></a><a class="yellow"></a></span>
										<span>数量：<input class="input-area" type="number" min="1" name="number" value="1"/>&nbsp;件 </span>
									</td>
								</tr>
								<tr class="button-area">
									<td>
										<button type="button" class="btn btn-default btn-lg bg_red">
										  <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true">&nbsp;加入购物车</span>
										</button>
										<button type="button" class="btn btn-default btn-lg collect">
										  <span class="glyphicon glyphicon-heart" aria-hidden="true">收藏商品</span>
										</button>
										<div class="ewm-box">
											<img src="{% static "img/detail/ewm.png" %}" />
										</div>
									</td>
								</tr>
							</tbody>
						</table>
						<!--条件筛选 end-->
					</div>
				</div>
			</div>
			<div class="container product-all-msg">{{ obj.content }}</div>
			<!--售后服务-->
			<div class="container after-sale-service">
				<h5 class="container-title">
						<span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span> 售后服务
						 <span class="glyphicon glyphicon-menu-down" aria-hidden="true"></span>
					</h5>
				<div class="row">
					<div class="col-xs-12 col-sm-3"></div>
					<div class="col-xs-12 col-sm-2 first"><img src="{% static "img/detail/aftersale01.png" %}" /></div>
					<div class="col-xs-12 col-sm-2"><img src="{% static "img/detail/aftersale02.png" %}" /></div>
					<div class="col-xs-12 col-sm-2"><img src="{% static "img/detail/aftersale03.png" %}" /></div>
					<div class="col-xs-12 col-sm-3"></div>
				</div>
			</div>
			<!--相关推荐-->
			<div class="container refer-recommend">
				<h5 class="container-title">相关推荐</h5>
				<div class="table-responsive">
					<table class="table">
						<tbody>
							<tr>
								<td>马甲卫衣</td>
								<td>卫衣裙女长款</td>
								<td>男童秋款卫衣</td>
								<td>卫衣棉衣外套女童</td>
								<td>卫衣女均码</td>
								<td>时尚冬季卫衣</td>
							</tr>
							<tr>
								<td>卫衣裙韩</td>
								<td>男童打底卫衣</td>
								<td>连帽可爱卫衣</td>
								<td>抓绒长款卫衣裙</td>
								<td>烫金黑色卫衣</td>
								<td>女士卫衣夏季套装</td>
							</tr>
							<tr>
								<td>大嘴猴抓绒卫衣</td>
								<td>宝宝保暖卫衣</td>
								<td>韩卫衣女蝙蝠</td>
								<td>图案加厚卫衣</td>
								<td>冬款加厚卫衣</td>
								<td>女童熊猫卫衣套装</td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<!--新品推荐-->
			<div class="container new-recommend">
				<h5 class="container-title">新品推荐</h5>
				<div class="table-responsive">
					<table class="table">
						<tbody>
							<tr>
								<td>LifeAfterLife/LAL纯色高领卫衣</td>
								<td>假两件连帽卫衣</td>
								<td>刺绣字母撞色圆领卫衣</td>
								<td>字母国旗贴布圆领卫衣</td>
								<td>趣味图案贴布圆领卫衣</td>
							</tr>
							<tr>
								<td>净版纯色卫衣 </td>
								<td>拉链拼接黑色圆领卫衣男士外套</td>
								<td>徐毛毛 box logo 连帽卫衣</td>
								<td>徐毛毛 创意刺绣图案圆领休闲卫衣</td>
								<td>简约纯色开衫卫衣 </td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>

			<!--文章推荐-->
			<div class="container essay-recommend">
				<h5 class="container-title">文章推荐</h5>
				<div class="table-responsive">
					<table class="table">
						<tbody>
							<tr>
								<td>一个Logo就足以帅炸你,你不知道的Logo T的魅力-识物</td>
								<td>最近流行的8大潮品,直男看了会流泪</td>
								<td>既要保暖又要前卫 2017秋冬季潮品推荐</td>
								<td>好物| 6件疯狂但却值得你购买的潮品</td>
								<td>千万别穿这些潮流运动品去跑步</td>
							</tr>
							<tr>
								<td>感谢这几招,让我潮品弄脏了不用再叫妈</td>
								<td>创意生活丨24个创意潮品让生活变简单</td>
								<td>好物| 6件疯狂但却值得你购买的潮品</td>
								<td>有关时尚 那些潮流文章不会告诉你的事儿</td>
								<td>时尚|“袖”潮盛行,看看在袖子上做过的文章</td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<!--店铺推荐-->
			<div class="container store-recommend">
				<div class="store-tabs" data-example-id="togglable-tabs">
					<ul id="storeTabs" class="nav nav-tabs" role="tablist">
						<li role="presentation" class="active">
							<a href="#store" id="store-tab" role="tab" data-toggle="tab" aria-controls="store" aria-expanded="true">店铺推荐</a>
						</li>
						<li role="presentation" class="">
							<a href="#recent-visit" role="tab" id="recent-visit-tab" data-toggle="tab" aria-controls="recent-visit" aria-expanded="false">最近浏览</a>
						</li>
						<a class="fl_right refresh">换一批&nbsp;<span class="glyphicon glyphicon-repeat" aria-hidden="true"></span></a>
					</ul>
					<div id="storeTabContent" class="tab-content">
						<div role="tabpanel" class="tab-pane fade active in" id="store" aria-labelledby="store-tab">
							<ul>
                                {% for item in storerecommend %}
								<li>
									<img src="{% static "img/detail/storerecommend1.png" %}" />
									<span class="item-name">Life After Life 假两件连帽卫衣 </span>
									<span class="item-price">479.00</span>
								</li>
                                {% endfor %}
							</ul>
						</div>
						<div role="tabpanel" class="tab-pane fade" id="recent-visit" aria-labelledby="recent-visit-tab">

						</div>
					</div>

				</div>
			</div>
		</main>

		{% include "footer.html" %}
		<script type="text/javascript" src="{% static "js/jquery-3.2.1.min.js" %}"></script>
		<script type="text/javascript" src="{% static "js/bootstrap/bootstrap.min.js" %}"></script>
		<script>
			$(function() {
				$('#remarkTabs a').click(function(e) {
					e.preventDefault();
					$(this).tab('show')
				})

				$('.allImg img').click(function(e) {
					e.preventDefault();
					$('.allImg img').each(function() {
						$(this).removeClass('active')
					})
					$(this).addClass('active');
					$('#detailPic').css('background-image', "url(" + $(this).attr('src') + ")");
				})

				$('.color-tr a').click(function(e) {
					e.preventDefault();
					$('.color-tr a').each(function() {
						$(this).removeClass('active');
						$(this).find("i").remove();
					})
					$(this).addClass('active');
					$(this).append('<i class="checked"></i>')
					$(this).children().css({
						'background': 'url("img/detail/check.png")',
						'position': 'absolute',
						'right': '0',
						'bottom': '0',
						'height': '12px',
						'width': '12px'
					});
				})
			})
		</script>
	</body>

</html>

templates/upload.html
{#{{ html|default:"no html" }} {#  default 是默认参数! #}
{#{% for i in list %}#}
{#{{ i }}#}
{#{% endfor %}#}
{##}
{##}
{#<form action="" method="POST" enctype="multipart/form-data">{% csrf_token %} {% csrf_token %}#}
{#    <!--action ="" 表单提交到当前页面,如果action="http://baidu.com/xxx" ,表单被提交到baidu.com-->#}
{#    <input type="file" name="gavin" accept="image/*"/>#}
{#    <input type="submit" value="上传"> <!-- type="submit" 点击后提交表单>#}
{#</form>#}